import { apiRequest } from './apiClient';
import type { AdminServiceKey } from './adminServicesApi';

export type ProjectStatus = 'active' | 'archived';

export type ProjectArchivedReason = 'manual' | 'end_date_reached';

export interface ProjectSupportAgent {
  id: string;
  name: string;
  email: string;
}

export interface ProjectSupportTicketRow {
  id: string;
  ticketNumber: string;
  subject: string;
  status: string;
  platformAssigneeName: string | null;
  createdAt: string;
}

export interface OrgProject {
  id: string;
  ownerType?: 'org' | 'tenant';
  orgId: string | null;
  tenantId?: string | null;
  name: string;
  autoGeneratedName: string;
  year: number;
  sequenceNumber: number;
  clientName: string;
  clientEmail?: string | null;
  description: string | null;
  startDate: string | null;
  endDate: string | null;
  reminderEmails?: string[];
  autoArchiveEnabled?: boolean;
  gracePeriodEndsAt?: string | null;
  expiryCleanupCompletedAt?: string | null;
  archivedAt?: string | null;
  archivedReason?: ProjectArchivedReason | null;
  enabledServices: AdminServiceKey[];
  status: ProjectStatus;
  createdBy: string;
  supportAgentId: string | null;
  supportAgent?: ProjectSupportAgent | null;
  createdAt: string;
  updatedAt: string;
  resourceCounts?: Record<string, number>;
}

export interface ProjectNamePreview {
  name: string;
  year: number;
  sequenceNumber: number;
}

export interface ProjectReportByProjectRow {
  projectId: string | null;
  projectName: string | null;
  clientName: string | null;
  totalDebit: number;
  transactionCount: number;
}

export interface ProjectReportByServiceRow {
  serviceKey: string;
  totalDebit: number;
  transactionCount: number;
}

interface ApiEnvelope<T> {
  success: boolean;
  message: string;
  data: T;
}

async function unwrap<T>(promise: Promise<ApiEnvelope<T>>): Promise<T> {
  const res = await promise;
  return res.data;
}

export async function fetchProjects(): Promise<OrgProject[]> {
  const data = await unwrap<{ projects: OrgProject[]; total: number }>(
    apiRequest('/api/v1/projects')
  );
  return data.projects;
}

export async function fetchProjectsForService(serviceKey: AdminServiceKey): Promise<OrgProject[]> {
  const data = await unwrap<{ projects: OrgProject[]; total: number }>(
    apiRequest(`/api/v1/projects/for-service/${serviceKey}`)
  );
  return data.projects;
}

export async function fetchProjectClientNames(): Promise<string[]> {
  const data = await unwrap<{ clientNames: string[] }>(
    apiRequest('/api/v1/projects/client-names')
  );
  return data.clientNames;
}

export async function fetchProject(id: string): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(apiRequest(`/api/v1/projects/${id}`));
  return data.project;
}

export interface ProjectElasticResource {
  id: string;
  name: string;
  ipAddress: string;
  username: string;
  protocol: string;
  assignedUsers: Array<{ email: string | null; username: string | null }>;
}

export async function fetchProjectElasticResources(
  projectId: string
): Promise<ProjectElasticResource[]> {
  const data = await unwrap<{ resources: ProjectElasticResource[]; total: number }>(
    apiRequest(`/api/v1/projects/${projectId}/resources/elastic-servers`)
  );
  return data.resources;
}

export async function fetchProjectSupportTickets(
  projectId: string
): Promise<ProjectSupportTicketRow[]> {
  const data = await unwrap<{ tickets: ProjectSupportTicketRow[] }>(
    apiRequest(`/api/v1/projects/${projectId}/support-tickets`)
  );
  return data.tickets;
}

export async function previewProjectName(): Promise<ProjectNamePreview> {
  return unwrap(apiRequest('/api/v1/projects/name-preview'));
}

export interface SupportAgentPreview {
  _id: string;
  name: string;
  email: string;
}

export async function fetchSupportAgentPreview(): Promise<SupportAgentPreview | null> {
  const data = await unwrap<{ agent: SupportAgentPreview | null }>(
    apiRequest('/api/v1/projects/support-agent-preview')
  );
  return data.agent;
}

export async function fetchSupportAgentsListForSuperAdmin(): Promise<SupportAgentPreview[]> {
  const data = await unwrap<{ agents: SupportAgentPreview[] }>(
    apiRequest('/api/v1/projects/support-agents-list')
  );
  return data.agents;
}

export async function createProject(input: {
  clientName: string;
  name?: string;
  description?: string;
  startDate?: string;
  endDate?: string;
  enabledServices: AdminServiceKey[];
  clientEmail?: string;
  autoArchiveEnabled?: boolean;
  supportAgentId?: string;
}): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest('/api/v1/projects', {
      method: 'POST',
      body: JSON.stringify(input),
    })
  );
  return data.project;
}

export async function fetchProjectSupportAgents(): Promise<ProjectSupportAgent[]> {
  const data = await unwrap<{ agents: ProjectSupportAgent[] }>(
    apiRequest('/api/v1/projects/support-agents')
  );
  return data.agents;
}

export async function updateProject(
  id: string,
  input: {
    name?: string;
    clientName?: string;
    description?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    clientEmail?: string | null;
    autoArchiveEnabled?: boolean;
    supportAgentId?: string | null;
  }
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(input),
    })
  );
  return data.project;
}

export async function addProjectServices(
  id: string,
  services: AdminServiceKey[]
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/${id}/services`, {
      method: 'POST',
      body: JSON.stringify({ services }),
    })
  );
  return data.project;
}

export async function removeProjectService(
  id: string,
  serviceKey: AdminServiceKey
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/${id}/services/${serviceKey}`, {
      method: 'DELETE',
    })
  );
  return data.project;
}

export async function archiveProject(id: string): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/${id}/archive`, { method: 'POST' })
  );
  return data.project;
}

export async function unarchiveProject(id: string): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/${id}/unarchive`, { method: 'POST' })
  );
  return data.project;
}

export async function fetchProjectCostReport(): Promise<ProjectReportByProjectRow[]> {
  const data = await unwrap<{ rows: ProjectReportByProjectRow[] }>(
    apiRequest('/api/v1/projects/reports/by-project')
  );
  return data.rows;
}

export async function fetchServiceCostReport(
  projectId?: string
): Promise<ProjectReportByServiceRow[]> {
  const qs = projectId ? `?projectId=${encodeURIComponent(projectId)}` : '';
  const data = await unwrap<{ rows: ProjectReportByServiceRow[] }>(
    apiRequest(`/api/v1/projects/reports/by-service${qs}`)
  );
  return data.rows;
}

/** Super-admin: list projects for an organization owner. */
export async function fetchProjectsForAdmin(adminId: string): Promise<OrgProject[]> {
  const data = await unwrap<{ projects: OrgProject[]; total: number }>(
    apiRequest(`/api/v1/projects/admins/${adminId}`)
  );
  return data.projects;
}

export async function previewProjectNameForAdmin(adminId: string): Promise<ProjectNamePreview> {
  return unwrap(apiRequest(`/api/v1/projects/admins/${adminId}/name-preview`));
}

export async function fetchEligibleProjectServicesForAdmin(
  adminId: string
): Promise<AdminServiceKey[]> {
  const data = await unwrap<{ services: AdminServiceKey[] }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/eligible-services`)
  );
  return data.services;
}

export async function createProjectForAdmin(
  adminId: string,
  input: {
    clientName: string;
    name?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    enabledServices: AdminServiceKey[];
    clientEmail?: string;
    autoArchiveEnabled?: boolean;
    supportAgentId?: string;
  }
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/admins/${adminId}`, {
      method: 'POST',
      body: JSON.stringify(input),
    })
  );
  return data.project;
}

export async function addProjectServicesForAdmin(
  adminId: string,
  projectId: string,
  services: AdminServiceKey[]
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/${projectId}/services`, {
      method: 'POST',
      body: JSON.stringify({ services }),
    })
  );
  return data.project;
}

export async function fetchProjectForAdmin(
  adminId: string,
  projectId: string
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/${projectId}`)
  );
  return data.project;
}

export async function fetchServiceCostReportForAdmin(
  adminId: string,
  projectId: string
): Promise<ProjectReportByServiceRow[]> {
  const data = await unwrap<{ rows: ProjectReportByServiceRow[] }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/${projectId}/reports/by-service`)
  );
  return data.rows;
}

/** Super-admin: list projects for a white-label tenant. */
export async function fetchProjectForTenant(
  tenantId: string,
  projectId: string
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/${projectId}`)
  );
  return data.project;
}

export async function fetchProjectsForTenant(tenantId: string): Promise<OrgProject[]> {
  const data = await unwrap<{ projects: OrgProject[]; total: number }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}`)
  );
  return data.projects;
}

export async function previewProjectNameForTenant(tenantId: string): Promise<ProjectNamePreview> {
  return unwrap(apiRequest(`/api/v1/projects/tenants/${tenantId}/name-preview`));
}

export async function fetchEligibleProjectServicesForTenant(
  tenantId: string
): Promise<AdminServiceKey[]> {
  const data = await unwrap<{ services: AdminServiceKey[] }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/eligible-services`)
  );
  return data.services;
}

export async function fetchProjectClientNamesForTenant(tenantId: string): Promise<string[]> {
  const data = await unwrap<{ clientNames: string[] }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/client-names`)
  );
  return data.clientNames;
}

export async function createProjectForTenant(
  tenantId: string,
  input: {
    clientName: string;
    name?: string;
    description?: string;
    startDate?: string;
    endDate?: string;
    enabledServices: AdminServiceKey[];
    clientEmail?: string;
    autoArchiveEnabled?: boolean;
    supportAgentId?: string;
  }
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}`, {
      method: 'POST',
      body: JSON.stringify(input),
    })
  );
  return data.project;
}

export async function addProjectServicesForTenant(
  tenantId: string,
  projectId: string,
  services: AdminServiceKey[]
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/${projectId}/services`, {
      method: 'POST',
      body: JSON.stringify({ services }),
    })
  );
  return data.project;
}

export async function updateProjectForAdmin(
  adminId: string,
  projectId: string,
  input: {
    clientName?: string;
    name?: string;
    description?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    supportAgentId?: string | null;
  }
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/${projectId}`, {
      method: 'PATCH',
      body: JSON.stringify(input),
    })
  );
  return data.project;
}

export async function updateProjectForTenant(
  tenantId: string,
  projectId: string,
  input: {
    clientName?: string;
    name?: string;
    description?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    supportAgentId?: string | null;
  }
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/${projectId}`, {
      method: 'PATCH',
      body: JSON.stringify(input),
    })
  );
  return data.project;
}

export async function archiveProjectForTenant(
  tenantId: string,
  projectId: string
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/${projectId}/archive`, {
      method: 'POST',
    })
  );
  return data.project;
}

export async function deleteProjectForTenant(
  tenantId: string,
  projectId: string
): Promise<{
  projectId: string;
  deleted: {
    catalogVms: number;
    dedicatedServers: number;
    managedVms: number;
    externalVms: number;
    externalAssignments: number;
  };
}> {
  const data = await unwrap<{
    projectId: string;
    deleted: {
      catalogVms: number;
      dedicatedServers: number;
      managedVms: number;
      externalVms: number;
      externalAssignments: number;
    };
  }>(
    apiRequest(`/api/v1/projects/tenants/${tenantId}/${projectId}`, {
      method: 'DELETE',
    })
  );
  return data;
}

export async function archiveProjectForAdmin(
  adminId: string,
  projectId: string
): Promise<OrgProject> {
  const data = await unwrap<{ project: OrgProject }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/${projectId}/archive`, {
      method: 'POST',
    })
  );
  return data.project;
}

export async function deleteProjectForAdmin(
  adminId: string,
  projectId: string
): Promise<{
  projectId: string;
  deleted: {
    catalogVms: number;
    dedicatedServers: number;
    managedVms: number;
    externalVms: number;
    externalAssignments: number;
  };
}> {
  const data = await unwrap<{
    projectId: string;
    deleted: {
      catalogVms: number;
      dedicatedServers: number;
      managedVms: number;
      externalVms: number;
      externalAssignments: number;
    };
  }>(
    apiRequest(`/api/v1/projects/admins/${adminId}/${projectId}`, {
      method: 'DELETE',
    })
  );
  return data;
}

export const PROJECT_SERVICE_LABELS: Record<AdminServiceKey, string> = {
  'create-vm': 'VM Catalog',
  'dedicated-server': 'Dedicated Server',
  'vm-management': 'VPS Hosting',
  'elastic-servers': 'External VM',
  'my-vms': 'My VM Dashboard',
  azure: 'Azure Lab',
  aws: 'AWS Lab',
  gcp: 'GCP Lab',
  'cloud-labs': 'Cloud Labs',
  docs: 'Documentation',
  'machine-manager': 'Machine Manager',
};

/** Prefer API label when present; fall back to static map / raw key. */
export function resolveProjectServiceLabel(
  key: string,
  apiLabel?: string | null,
  labelMap?: Record<string, string>
): string {
  if (apiLabel) return apiLabel;
  if (labelMap?.[key]) return labelMap[key];
  if (key in PROJECT_SERVICE_LABELS) {
    return PROJECT_SERVICE_LABELS[key as AdminServiceKey];
  }
  return key;
}
