import mongoose from 'mongoose';
import { ProjectModel, type IProject, type ProjectOwnerType, type ProjectStatus } from '../../models/project.model';
import { OrganizationAccessRequestModel } from '../../models/organizationAccessRequest.model';
import { User, type IUser } from '../../models/user.model';
import { TenantUser } from '../../models/tenantUser.model';
import { Tenant } from '../../models/tenant.model';
import { CatalogVmModel } from '../../models/catalogVm.model';
import { DedicatedServerRequestModel } from '../../models/dedicatedServerRequest.model';
import { ExternalVMModel } from '../external-vm/external-vm.model';
import { ExternalVmUserAssignmentModel } from '../../models/externalVmUserAssignment.model';
import { ExternalVmTenantAssignmentModel } from '../../models/externalVmTenantAssignment.model';
import { VM } from '../vm/vm.model';
import { AdminWalletTransaction } from '../../models/adminWalletTransaction.model';
import { WalletTransaction } from '../../models/walletTransaction.model';
import {
  type AdminServiceKey,
  isAdminServiceKey,
} from '../../constants/adminServiceCatalog';
import { adminServicesService } from '../adminServices/adminServices.service';
import { tenantServiceConfigService } from '../tenant/tenantServiceConfig.service';
import { serviceCatalogService } from '../serviceCatalog/serviceCatalog.service';
import { resolvePlatformOrgOwnerId } from '../platformRbac/platformRbac.service';
import { assignProjectSupportAgent } from '../support/support.service';
import { Ticket } from '../support/support.model';
import {
  ConflictError,
  ForbiddenError,
  NotFoundError,
  ValidationError,
} from '../../utils/errors';
import type {
  AddProjectServicesInput,
  CreateProjectInput,
  UpdateProjectInput,
} from './projects.validation';

export interface ProjectSupportAgentPublic {
  id: string;
  name: string;
  email: string;
}

export interface ProjectSupportTicketRow {
  id: string;
  ticketNumber: string;
  subject: string;
  status: string;
  platformAssigneeName: string | null;
  createdAt: string;
}

export interface ProjectPublic {
  id: string;
  ownerType: ProjectOwnerType;
  orgId: string | null;
  tenantId: string | null;
  name: string;
  autoGeneratedName: string;
  year: number;
  sequenceNumber: number;
  clientName: string;
  clientEmail: string | null;
  description: string | null;
  startDate: string | null;
  endDate: string | null;
  reminderEmails: string[];
  autoArchiveEnabled: boolean;
  gracePeriodEndsAt: string | null;
  expiryCleanupCompletedAt: string | null;
  archivedAt: string | null;
  archivedReason: 'manual' | 'end_date_reached' | null;
  enabledServices: AdminServiceKey[];
  status: ProjectStatus;
  createdBy: string;
  supportAgentId: string | null;
  supportAgent: ProjectSupportAgentPublic | null;
  createdAt: string;
  updatedAt: string;
  resourceCounts?: Record<string, number>;
}

export interface ProjectReportByProjectRow {
  projectId: string | null;
  projectName: string | null;
  clientName: string | null;
  totalDebit: number;
  transactionCount: number;
}

export interface ProjectReportByServiceRow {
  serviceKey: string;
  totalDebit: number;
  transactionCount: number;
}

export interface ProjectElasticResource {
  id: string;
  name: string;
  ipAddress: string;
  username: string;
  protocol: string;
  assignedUsers: Array<{ email: string | null; username: string | null }>;
}

async function listElasticResourcesForOwner(
  projectId: mongoose.Types.ObjectId,
  owner: { tenantId: string } | { adminId: string }
): Promise<ProjectElasticResource[]> {
  // Match the project resource count (projectId only). Ownership was already
  // checked on the Project document before this helper is called.
  const docs = await ExternalVMModel.find({ projectId })
    .select('_id name ipAddress username protocol assignedTo assignedTenantUserId')
    .sort({ ipAddress: 1, username: 1 })
    .lean();
  if (docs.length === 0) return [];

  const vmIds = docs.map((d) => d._id);
  const assignedByVm = new Map<string, Array<{ email: string | null; username: string | null }>>();

  if ('tenantId' in owner) {
    const tenantOid = new mongoose.Types.ObjectId(owner.tenantId);
    const rows = await ExternalVmTenantAssignmentModel.find({
      tenantId: tenantOid,
      externalVmId: { $in: vmIds },
      $or: [{ status: 'active' }, { status: { $exists: false } }, { status: null }],
    })
      .select('externalVmId tenantUserId')
      .lean();
    const userIds = [...new Set(rows.map((r) => r.tenantUserId.toString()))].map(
      (id) => new mongoose.Types.ObjectId(id)
    );
    const users = userIds.length
      ? await TenantUser.find({ _id: { $in: userIds } }).select('email username').lean()
      : [];
    const userById = new Map(users.map((u) => [u._id.toString(), u]));
    for (const row of rows) {
      const u = userById.get(row.tenantUserId.toString());
      const key = row.externalVmId.toString();
      const list = assignedByVm.get(key) ?? [];
      list.push({ email: u?.email ?? null, username: u?.username ?? null });
      assignedByVm.set(key, list);
    }
    const missing = docs.filter(
      (d) => !assignedByVm.has(d._id.toString()) && d.assignedTenantUserId
    );
    if (missing.length > 0) {
      const legacyIds = missing.map((d) => d.assignedTenantUserId!);
      const legacyUsers = await TenantUser.find({ _id: { $in: legacyIds } })
        .select('email username')
        .lean();
      const legacyById = new Map(legacyUsers.map((u) => [u._id.toString(), u]));
      for (const d of missing) {
        const u = legacyById.get(d.assignedTenantUserId!.toString());
        assignedByVm.set(d._id.toString(), [
          { email: u?.email ?? null, username: u?.username ?? null },
        ]);
      }
    }
  } else {
    const rows = await ExternalVmUserAssignmentModel.find({
      externalVmId: { $in: vmIds },
      $or: [{ status: 'active' }, { status: { $exists: false } }, { status: null }],
    })
      .select('externalVmId userId')
      .lean();
    const userIds = [...new Set(rows.map((r) => r.userId.toString()))].map(
      (id) => new mongoose.Types.ObjectId(id)
    );
    const users = userIds.length
      ? await User.find({ _id: { $in: userIds } }).select('email username').lean()
      : [];
    const userById = new Map(users.map((u) => [u._id.toString(), u]));
    for (const row of rows) {
      const u = userById.get(row.userId.toString());
      const key = row.externalVmId.toString();
      const list = assignedByVm.get(key) ?? [];
      list.push({ email: u?.email ?? null, username: u?.username ?? null });
      assignedByVm.set(key, list);
    }
    const missing = docs.filter((d) => !assignedByVm.has(d._id.toString()) && d.assignedTo);
    if (missing.length > 0) {
      const legacyIds = missing.map((d) => d.assignedTo!);
      const legacyUsers = await User.find({ _id: { $in: legacyIds } })
        .select('email username')
        .lean();
      const legacyById = new Map(legacyUsers.map((u) => [u._id.toString(), u]));
      for (const d of missing) {
        const u = legacyById.get(d.assignedTo!.toString());
        assignedByVm.set(d._id.toString(), [
          { email: u?.email ?? null, username: u?.username ?? null },
        ]);
      }
    }
  }

  return docs.map((d) => ({
    id: d._id.toString(),
    name: d.name,
    ipAddress: d.ipAddress,
    username: d.username,
    protocol: d.protocol,
    assignedUsers: assignedByVm.get(d._id.toString()) ?? [],
  }));
}

function normalizeClientEmail(email?: string | null): string | undefined {
  const trimmed = email?.trim().toLowerCase();
  return trimmed || undefined;
}

function markProjectArchived(
  doc: IProject,
  reason: 'manual' | 'end_date_reached'
): void {
  doc.status = 'archived';
  doc.archivedReason = reason;
  doc.archivedAt = new Date();
}

function markProjectUnarchived(doc: IProject): void {
  doc.status = 'active';
  doc.archivedAt = undefined;
  doc.archivedReason = undefined;
  doc.gracePeriodEndsAt = undefined;
  doc.expiryCleanupCompletedAt = undefined;
}

function supportAgentFromDoc(doc: IProject): ProjectSupportAgentPublic | null {
  const raw = doc.supportAgentId as IUser | mongoose.Types.ObjectId | null | undefined;
  if (!raw || raw instanceof mongoose.Types.ObjectId) return null;
  return {
    id: raw._id.toString(),
    name: raw.name?.trim() || raw.email,
    email: raw.email,
  };
}

async function enrichWithSupportAgent(doc: IProject): Promise<IProject> {
  if (!doc.populated('supportAgentId')) {
    await doc.populate({ path: 'supportAgentId', select: 'name email isActive role' });
  }
  return doc;
}

async function applySupportAgentUpdate(
  doc: IProject,
  supportAgentId: string | null | undefined
): Promise<void> {
  if (supportAgentId === undefined) return;
  if (supportAgentId === null || supportAgentId === '') {
    doc.supportAgentId = undefined;
    return;
  }
  if (!mongoose.Types.ObjectId.isValid(supportAgentId)) {
    throw new ValidationError('Invalid support agent id.');
  }
  const agent = await User.findOne({
    _id: new mongoose.Types.ObjectId(supportAgentId),
    role: 'support_agent',
    isActive: true,
  }).select('_id');
  if (!agent) {
    throw new ValidationError('Support agent not found or inactive.');
  }
  doc.supportAgentId = agent._id;
}

async function toPublicWithAgent(
  doc: IProject,
  resourceCounts?: Record<string, number>
): Promise<ProjectPublic> {
  await enrichWithSupportAgent(doc);
  return toPublic(doc, resourceCounts);
}

function applyProjectUpdateFields(doc: IProject, input: UpdateProjectInput): void {
  if (input.name !== undefined) doc.name = input.name.trim();
  if (input.clientName !== undefined) doc.clientName = input.clientName.trim();
  if (input.description !== undefined) {
    doc.description = input.description?.trim() || undefined;
  }
  if (input.startDate !== undefined) doc.startDate = input.startDate ?? undefined;
  if (input.clientEmail !== undefined) {
    doc.clientEmail = normalizeClientEmail(input.clientEmail);
  }
  if (input.endDate !== undefined) {
    const next = input.endDate ?? undefined;
    const prevMs = doc.endDate?.getTime();
    doc.endDate = next;
    if (next?.getTime() !== prevMs) {
      doc.expiryWarningSentFor = undefined;
      doc.gracePeriodEndsAt = undefined;
      doc.expiryCleanupCompletedAt = undefined;
    }
  }
  if (input.autoArchiveEnabled !== undefined) {
    doc.autoArchiveEnabled = input.autoArchiveEnabled;
  }
}

function toPublic(doc: IProject, resourceCounts?: Record<string, number>): ProjectPublic {
  return {
    id: doc._id.toString(),
    ownerType: doc.ownerType || 'org',
    orgId: doc.orgId ?? null,
    tenantId: doc.tenantId ?? null,
    name: doc.name,
    autoGeneratedName: doc.autoGeneratedName,
    year: doc.year,
    sequenceNumber: doc.sequenceNumber,
    clientName: doc.clientName,
    clientEmail: doc.clientEmail ?? null,
    description: doc.description ?? null,
    startDate: doc.startDate ? doc.startDate.toISOString() : null,
    endDate: doc.endDate ? doc.endDate.toISOString() : null,
    reminderEmails: [...(doc.reminderEmails ?? [])],
    autoArchiveEnabled: doc.autoArchiveEnabled !== false,
    gracePeriodEndsAt: doc.gracePeriodEndsAt ? doc.gracePeriodEndsAt.toISOString() : null,
    expiryCleanupCompletedAt: doc.expiryCleanupCompletedAt
      ? doc.expiryCleanupCompletedAt.toISOString()
      : null,
    archivedAt: doc.archivedAt ? doc.archivedAt.toISOString() : null,
    archivedReason: doc.archivedReason ?? null,
    enabledServices: [...doc.enabledServices],
    status: doc.status,
    createdBy: doc.createdBy.toString(),
    supportAgentId: supportAgentFromDoc(doc)?.id ?? doc.supportAgentId?.toString() ?? null,
    supportAgent: supportAgentFromDoc(doc),
    createdAt: doc.createdAt.toISOString(),
    updatedAt: doc.updatedAt.toISOString(),
    ...(resourceCounts ? { resourceCounts } : {}),
  };
}

function slugifyOrgName(raw: string): string {
  const slug = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return slug || 'org';
}

async function resolveOrgSlug(orgId: string): Promise<string> {
  const access = await OrganizationAccessRequestModel.findOne({
    userId: new mongoose.Types.ObjectId(orgId),
    status: 'approved',
  })
    .select('companyName')
    .lean();
  if (access?.companyName) return slugifyOrgName(access.companyName);

  const user = await User.findById(orgId).select('email').lean();
  if (user?.email) {
    const local = String(user.email).split('@')[0] || 'org';
    return slugifyOrgName(local);
  }
  return 'org';
}

function padSequence(n: number): string {
  return String(n).padStart(3, '0');
}

async function resolveTenantSlug(tenantId: string): Promise<string> {
  const tenant = await Tenant.findById(tenantId).select('name slug').lean();
  if (tenant?.slug) return slugifyOrgName(tenant.slug);
  if (tenant?.name) return slugifyOrgName(tenant.name);
  return 'tenant';
}

async function assertTenantExists(tenantId: string): Promise<void> {
  if (!mongoose.Types.ObjectId.isValid(tenantId)) {
    throw new ValidationError('Invalid tenant id.');
  }
  const tenant = await Tenant.findById(tenantId).select('_id').lean();
  if (!tenant) throw new NotFoundError('Tenant not found.');
}

async function nextSequenceForOwner(params: {
  ownerType: ProjectOwnerType;
  orgId?: string;
  tenantId?: string;
  year: number;
}): Promise<number> {
  const filter =
    params.ownerType === 'tenant'
      ? { ownerType: 'tenant' as const, tenantId: params.tenantId, year: params.year }
      : {
          ownerType: 'org' as const,
          // Explicitly require orgId to be the exact string — never match null/missing orgId.
          orgId: { $eq: params.orgId },
          year: params.year,
        };
  const latest = await ProjectModel.findOne(filter)
    .sort({ sequenceNumber: -1 })
    .select('sequenceNumber')
    .lean();
  return (latest?.sequenceNumber ?? 0) + 1;
}

async function nextSequence(orgId: string, year: number): Promise<number> {
  return nextSequenceForOwner({ ownerType: 'org', orgId, year });
}

async function assertOrgOwner(userId: string): Promise<{ orgId: string }> {
  const user = await User.findById(userId).select('role orgOwnerId isActive').lean();
  if (!user || !user.isActive || user.role !== 'admin') {
    throw new ForbiddenError('Only organization admins can manage projects.');
  }
  if (user.orgOwnerId) {
    throw new ForbiddenError('Only the organization owner can manage projects.');
  }
  const orgId = resolvePlatformOrgOwnerId({
    _id: user._id,
    role: user.role,
    orgOwnerId: user.orgOwnerId,
  });
  if (!orgId) throw new ForbiddenError('Organization context required.');
  return { orgId };
}

/** Resolve org owner id for super-admin acting on a customer admin. */
async function resolveTargetOrgOwnerId(adminId: string): Promise<string> {
  if (!mongoose.Types.ObjectId.isValid(adminId)) {
    throw new ValidationError('Invalid admin id.');
  }
  const user = await User.findById(adminId).select('role orgOwnerId isActive').lean();
  if (!user || !user.isActive || user.role !== 'admin') {
    throw new NotFoundError('Organization admin not found.');
  }
  if (user.orgOwnerId) {
    throw new ValidationError(
      'Projects belong to the organization owner. Open the owner account, not an operator.'
    );
  }
  const orgId = resolvePlatformOrgOwnerId({
    _id: user._id,
    role: user.role,
    orgOwnerId: user.orgOwnerId,
  });
  if (!orgId) throw new ValidationError('Organization context required.');
  return orgId;
}

async function resolveSupportAgentOverride(
  overrideSupportAgentId: string
): Promise<mongoose.Types.ObjectId> {
  if (!mongoose.Types.ObjectId.isValid(overrideSupportAgentId)) {
    throw new ValidationError('Invalid support agent id.');
  }
  const agent = await User.findOne({
    _id: new mongoose.Types.ObjectId(overrideSupportAgentId),
    role: 'support_agent',
    isActive: true,
  }).select('_id');
  if (!agent) {
    throw new ValidationError('Support agent not found or inactive.');
  }
  return agent._id;
}

async function finalizeNewProject(
  doc: IProject,
  enabledServices: AdminServiceKey[],
  overrideSupportAgentId?: string
): Promise<ProjectPublic> {
  if (overrideSupportAgentId) {
    doc.supportAgentId = await resolveSupportAgentOverride(overrideSupportAgentId);
    await doc.save();
    await User.findByIdAndUpdate(doc.supportAgentId, { $inc: { assignedProjectCount: 1 } });
  } else {
    const agent = await assignProjectSupportAgent(doc._id.toString());
    if (agent) {
      doc.supportAgentId = agent._id;
      await doc.save();
    }
  }
  return toPublicWithAgent(doc, Object.fromEntries(enabledServices.map((k) => [k, 0])));
}

async function createForOrg(
  orgId: string,
  createdByUserId: string,
  input: CreateProjectInput,
  options?: { bypassServiceCheck?: boolean; supportAgentId?: string }
): Promise<ProjectPublic> {
  if (!orgId || typeof orgId !== 'string') {
    throw new ValidationError('Organization ID is required to create a project.');
  }
  let enabledServices: AdminServiceKey[];
  if (options?.bypassServiceCheck) {
    // Super-admin path: trust the requested services without checking org's active service list.
    enabledServices = input.enabledServices.filter(isAdminServiceKey) as AdminServiceKey[];
  } else {
    const allowed = await getActiveOrgServiceKeys(orgId);
    enabledServices = assertServicesSubset(input.enabledServices, allowed);
  }

  const year = new Date().getUTCFullYear();
  const sequenceNumber = await nextSequenceForOwner({ ownerType: 'org', orgId, year });
  const slug = await resolveOrgSlug(orgId);
  const autoGeneratedName = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
  const name = (input.name?.trim() || autoGeneratedName).slice(0, 200);

  const doc = await ProjectModel.create({
    ownerType: 'org',
    orgId,
    name,
    autoGeneratedName,
    year,
    sequenceNumber,
    clientName: input.clientName.trim(),
    clientEmail: normalizeClientEmail(input.clientEmail),
    description: input.description?.trim() || undefined,
    startDate: input.startDate ?? undefined,
    endDate: input.endDate ?? undefined,
    autoArchiveEnabled: input.autoArchiveEnabled !== false,
    enabledServices,
    status: 'active',
    createdBy: new mongoose.Types.ObjectId(createdByUserId),
  });

  return finalizeNewProject(doc, enabledServices, options?.supportAgentId);
}

async function createForTenant(
  tenantId: string,
  createdByUserId: string,
  input: CreateProjectInput,
  options?: { supportAgentId?: string }
): Promise<ProjectPublic> {
  const allowed = await getActiveTenantServiceKeys(tenantId);
  const enabledServices = assertServicesSubset(input.enabledServices, allowed);

  const year = new Date().getUTCFullYear();
  const sequenceNumber = await nextSequenceForOwner({ ownerType: 'tenant', tenantId, year });
  const slug = await resolveTenantSlug(tenantId);
  const autoGeneratedName = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
  const name = (input.name?.trim() || autoGeneratedName).slice(0, 200);

  const doc = await ProjectModel.create({
    ownerType: 'tenant',
    tenantId,
    name,
    autoGeneratedName,
    year,
    sequenceNumber,
    clientName: input.clientName.trim(),
    clientEmail: normalizeClientEmail(input.clientEmail),
    description: input.description?.trim() || undefined,
    startDate: input.startDate ?? undefined,
    endDate: input.endDate ?? undefined,
    autoArchiveEnabled: input.autoArchiveEnabled !== false,
    enabledServices,
    status: 'active',
    createdBy: new mongoose.Types.ObjectId(createdByUserId),
  });

  return finalizeNewProject(doc, enabledServices, options?.supportAgentId);
}

async function getActiveOrgServiceKeys(orgId: string): Promise<Set<AdminServiceKey>> {
  const [services, assignable] = await Promise.all([
    adminServicesService.listMine(new mongoose.Types.ObjectId(orgId)),
    serviceCatalogService.listAssignableKeys('admin'),
  ]);
  const assignableSet = new Set(assignable);
  return new Set(
    services
      .filter((s) => s.status === 'active')
      .map((s) => s.serviceKey)
      .filter(isAdminServiceKey)
      .filter((key) => assignableSet.has(key))
  );
}

async function getActiveTenantServiceKeys(tenantId: string): Promise<Set<AdminServiceKey>> {
  const [services, assignable] = await Promise.all([
    tenantServiceConfigService.listServicesForTenant(tenantId),
    serviceCatalogService.listAssignableKeys('tenant'),
  ]);
  const assignableSet = new Set(assignable);
  return new Set(
    services
      .filter((s) => s.status === 'active')
      .map((s) => s.serviceKey)
      .filter(isAdminServiceKey)
      .filter((key) => assignableSet.has(key))
  );
}

function assertServicesSubset(
  requested: string[],
  allowed: Set<AdminServiceKey>
): AdminServiceKey[] {
  const out: AdminServiceKey[] = [];
  for (const key of requested) {
    if (!isAdminServiceKey(key)) {
      throw new ValidationError(`Unknown service "${key}".`);
    }
    if (!allowed.has(key)) {
      throw new ValidationError(
        `Service "${key}" is not enabled for this organization.`
      );
    }
    if (!out.includes(key)) out.push(key);
  }
  return out;
}

async function cascadeDeleteProjectResources(projectId: mongoose.Types.ObjectId): Promise<{
  catalogVms: number;
  dedicatedServers: number;
  managedVms: number;
  externalVms: number;
  externalAssignments: number;
}> {
  const externalVms = await ExternalVMModel.find({ projectId }).select('_id inventoryLocked').lean();
  const locked = externalVms.filter((vm) => vm.inventoryLocked);
  if (locked.length > 0) {
    throw new ConflictError(
      `Cannot delete project: ${locked.length} inventory-locked elastic server(s) are still assigned. Unlock them first.`
    );
  }

  const externalVmIds = externalVms.map((vm) => vm._id);
  const [platformAssignResult, tenantAssignResult] = await Promise.all([
    externalVmIds.length
      ? ExternalVmUserAssignmentModel.deleteMany({ externalVmId: { $in: externalVmIds } })
      : Promise.resolve({ deletedCount: 0 }),
    externalVmIds.length
      ? ExternalVmTenantAssignmentModel.deleteMany({ externalVmId: { $in: externalVmIds } })
      : Promise.resolve({ deletedCount: 0 }),
  ]);

  const [catalogResult, dedicatedResult, managedResult, externalResult] = await Promise.all([
    CatalogVmModel.deleteMany({ projectId }),
    DedicatedServerRequestModel.deleteMany({ projectId }),
    VM.deleteMany({ projectId }),
    externalVmIds.length
      ? ExternalVMModel.deleteMany({ _id: { $in: externalVmIds } })
      : Promise.resolve({ deletedCount: 0 }),
  ]);

  return {
    catalogVms: catalogResult.deletedCount ?? 0,
    dedicatedServers: dedicatedResult.deletedCount ?? 0,
    managedVms: managedResult.deletedCount ?? 0,
    externalVms: externalResult.deletedCount ?? 0,
    externalAssignments:
      (platformAssignResult.deletedCount ?? 0) + (tenantAssignResult.deletedCount ?? 0),
  };
}

async function countResourcesForService(
  projectId: mongoose.Types.ObjectId,
  serviceKey: AdminServiceKey
): Promise<number> {
  switch (serviceKey) {
    case 'create-vm':
      return CatalogVmModel.countDocuments({ projectId });
    case 'dedicated-server':
      return DedicatedServerRequestModel.countDocuments({ projectId });
    case 'vm-management':
      return VM.countDocuments({ projectId });
    case 'elastic-servers':
      return ExternalVMModel.countDocuments({ projectId });
    default:
      // Azure/AWS/GCP not stamped in V1 — treat as zero until wired.
      return 0;
  }
}

async function resourceCountsByService(
  project: IProject
): Promise<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const key of project.enabledServices) {
    counts[key] = await countResourcesForService(project._id, key);
  }
  return counts;
}

export class ProjectsService {
  async previewName(userId: string): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const { orgId } = await assertOrgOwner(userId);
    return this.previewNameForOrg(orgId);
  }

  async previewNameForOrg(
    orgId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const year = new Date().getUTCFullYear();
    const sequenceNumber = await nextSequence(orgId, year);
    const slug = await resolveOrgSlug(orgId);
    const name = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
    return { name, year, sequenceNumber };
  }

  async list(userId: string): Promise<ProjectPublic[]> {
    const { orgId } = await assertOrgOwner(userId);
    return this.listForOrg(orgId);
  }

  async listForOrg(orgId: string): Promise<ProjectPublic[]> {
    const oid = String(orgId);

    // Backfill legacy org projects created before ownerType existed.
    await ProjectModel.updateMany(
      {
        orgId: oid,
        $or: [{ ownerType: { $exists: false } }, { ownerType: null }],
        $and: [
          {
            $or: [{ tenantId: { $exists: false } }, { tenantId: null }, { tenantId: '' }],
          },
        ],
      },
      { $set: { ownerType: 'org' } }
    );

    const docs = await ProjectModel.find({
      orgId: oid,
      $and: [
        {
          $or: [
            { ownerType: 'org' },
            { ownerType: { $exists: false } },
            { ownerType: null },
          ],
        },
        {
          $or: [{ tenantId: { $exists: false } }, { tenantId: null }, { tenantId: '' }],
        },
      ],
    }).sort({ createdAt: -1 });

    return docs.map((d) => toPublic(d));
  }

  async getById(userId: string, projectId: string): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    const resourceCounts = await resourceCountsByService(doc);
    return toPublicWithAgent(doc, resourceCounts);
  }

  async create(userId: string, input: CreateProjectInput): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    return createForOrg(orgId, userId, input);
  }

  /** Super-admin: list projects for an organization owner admin. */
  async listForAdmin(targetAdminId: string): Promise<ProjectPublic[]> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const projects = await this.listForOrg(orgId);
    return projects;
  }

  /** Super-admin: preview next project name for an organization. */
  async previewNameForAdmin(
    targetAdminId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    return this.previewNameForOrg(orgId);
  }

  /** Super-admin: create a project owned by the organization (visible to org admin). */
  async createForAdmin(
    targetAdminId: string,
    createdByUserId: string,
    input: CreateProjectInput
  ): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    // Bypass service check — super-admin is trusted to assign any service.
    return createForOrg(orgId, createdByUserId, input, {
      bypassServiceCheck: true,
      supportAgentId: input.supportAgentId,
    });
  }

  /** Super-admin: active project-eligible services for an org. */
  async listEligibleServicesForAdmin(targetAdminId: string): Promise<AdminServiceKey[]> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    return [...(await getActiveOrgServiceKeys(orgId))];
  }

  /** Super-admin: add services to an org project. */
  async addServicesForAdmin(
    targetAdminId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    if (!doc.ownerType) {
      doc.ownerType = 'org';
    }

    const allowed = await getActiveOrgServiceKeys(orgId);
    const toAdd = assertServicesSubset(input.services, allowed);
    const merged = new Set([...doc.enabledServices, ...toAdd]);
    doc.enabledServices = [...merged] as AdminServiceKey[];
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  /** Super-admin: project detail for an organization. */
  async getByIdForAdmin(targetAdminId: string, projectId: string): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');
    return toPublicWithAgent(doc, await resourceCountsByService(doc));
  }

  /** Super-admin: service-wise wallet usage for one org project. */
  async reportByServiceForAdmin(
    targetAdminId: string,
    projectId: string
  ): Promise<ProjectReportByServiceRow[]> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    })
      .select('_id')
      .lean();
    if (!doc) throw new NotFoundError('Project not found.');

    const orgOid = new mongoose.Types.ObjectId(orgId);
    const rows = await AdminWalletTransaction.aggregate<{
      _id: string | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      {
        $match: {
          type: 'debit',
          projectId: doc._id,
          $or: [{ orgId: orgOid }, { userId: orgOid }],
        },
      },
      {
        $group: {
          _id: { $ifNull: ['$serviceKey', '$reason'] },
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    return rows.map((r) => ({
      serviceKey: r._id || 'unknown',
      totalDebit: Math.round(r.totalDebit * 100) / 100,
      transactionCount: r.transactionCount,
    }));
  }

  /** Super-admin: add services to a tenant project. */
  async addServicesForTenantBySuperAdmin(
    tenantId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    await assertTenantExists(tenantId);
    return this.addServicesForTenant(tenantId, projectId, input);
  }

  /** Super-admin: list projects for a white-label tenant. */
  async listForTenantBySuperAdmin(tenantId: string): Promise<ProjectPublic[]> {
    await assertTenantExists(tenantId);
    return this.listForTenant(tenantId);
  }

  async previewNameForTenantBySuperAdmin(
    tenantId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    await assertTenantExists(tenantId);
    return this.previewNameForTenant(tenantId);
  }

  async createForTenantBySuperAdmin(
    tenantId: string,
    createdByUserId: string,
    input: CreateProjectInput
  ): Promise<ProjectPublic> {
    await assertTenantExists(tenantId);
    return createForTenant(tenantId, createdByUserId, input, {
      supportAgentId: input.supportAgentId,
    });
  }

  async listEligibleServicesForTenantBySuperAdmin(tenantId: string): Promise<AdminServiceKey[]> {
    await assertTenantExists(tenantId);
    return this.listEligibleServicesForTenant(tenantId);
  }

  async listForTenant(tenantId: string): Promise<ProjectPublic[]> {
    const docs = await ProjectModel.find({ ownerType: 'tenant', tenantId }).sort({
      createdAt: -1,
    });
    return docs.map((d) => toPublic(d));
  }

  /** Returns distinct client names used in projects for this tenant. */
  async distinctClientNamesForTenant(tenantId: string): Promise<string[]> {
    const names: string[] = await ProjectModel.distinct('clientName', {
      ownerType: 'tenant',
      tenantId,
    });
    return names
      .filter((n): n is string => typeof n === 'string' && n.trim().length > 0)
      .sort((a, b) => a.localeCompare(b));
  }

  async previewNameForTenant(
    tenantId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const year = new Date().getUTCFullYear();
    const sequenceNumber = await nextSequenceForOwner({ ownerType: 'tenant', tenantId, year });
    const slug = await resolveTenantSlug(tenantId);
    const name = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
    return { name, year, sequenceNumber };
  }

  async createForTenantWorkspace(
    tenantId: string,
    createdByUserId: string,
    input: CreateProjectInput
  ): Promise<ProjectPublic> {
    return createForTenant(tenantId, createdByUserId, input);
  }

  async listEligibleServicesForTenant(tenantId: string): Promise<AdminServiceKey[]> {
    return [...(await getActiveTenantServiceKeys(tenantId))];
  }

  async getByIdForTenant(tenantId: string, projectId: string): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    const resourceCounts = await resourceCountsByService(doc);
    return toPublicWithAgent(doc, resourceCounts);
  }

  async listElasticResourcesForTenant(
    tenantId: string,
    projectId: string
  ): Promise<ProjectElasticResource[]> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    }).select('_id');
    if (!doc) throw new NotFoundError('Project not found.');
    return listElasticResourcesForOwner(doc._id, { tenantId });
  }

  async listElasticResources(userId: string, projectId: string): Promise<ProjectElasticResource[]> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    }).select('_id');
    if (!doc) throw new NotFoundError('Project not found.');
    return listElasticResourcesForOwner(doc._id, { adminId: orgId });
  }

  async updateForTenant(
    tenantId: string,
    projectId: string,
    input: UpdateProjectInput
  ): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be edited.');
    }
    applyProjectUpdateFields(doc, input);
    await applySupportAgentUpdate(doc, input.supportAgentId);
    await doc.save();
    return toPublicWithAgent(doc, await resourceCountsByService(doc));
  }

  async addServicesForTenant(
    tenantId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    const allowed = await getActiveTenantServiceKeys(tenantId);
    const toAdd = assertServicesSubset(input.services, allowed);
    doc.enabledServices = [...new Set([...doc.enabledServices, ...toAdd])] as AdminServiceKey[];
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async removeServiceForTenant(
    tenantId: string,
    projectId: string,
    serviceKey: string
  ): Promise<ProjectPublic> {
    if (!isAdminServiceKey(serviceKey)) {
      throw new ValidationError(`Unknown service "${serviceKey}".`);
    }
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    if (!doc.enabledServices.includes(serviceKey)) {
      throw new ValidationError(`Service "${serviceKey}" is not enabled on this project.`);
    }
    const count = await countResourcesForService(doc._id, serviceKey);
    if (count > 0) {
      throw new ValidationError(
        `Cannot remove "${serviceKey}" while ${count} resource(s) exist under this project.`
      );
    }
    doc.enabledServices = doc.enabledServices.filter((k) => k !== serviceKey);
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async archiveForTenant(tenantId: string, projectId: string): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Project is already archived.');
    }
    markProjectArchived(doc, 'manual');
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async unarchiveForTenant(tenantId: string, projectId: string): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'archived') {
      throw new ValidationError('Project is not archived.');
    }
    markProjectUnarchived(doc);
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  /** Super-admin: permanently delete a tenant project and all resources under it. */
  async deleteForTenant(
    tenantId: string,
    projectId: string
  ): Promise<{
    projectId: string;
    deleted: Awaited<ReturnType<typeof cascadeDeleteProjectResources>>;
  }> {
    await assertTenantExists(tenantId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');

    const deleted = await cascadeDeleteProjectResources(doc._id);
    await ProjectModel.deleteOne({ _id: doc._id });
    return { projectId: doc._id.toString(), deleted };
  }

  /** Super-admin: archive an organization project. */
  async archiveForAdmin(targetAdminId: string, projectId: string): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Project is already archived.');
    }
    markProjectArchived(doc, 'manual');
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async unarchiveForAdmin(targetAdminId: string, projectId: string): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'archived') {
      throw new ValidationError('Project is not archived.');
    }
    markProjectUnarchived(doc);
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  /** Super-admin: permanently delete an org project and all resources under it. */
  async deleteForAdmin(
    targetAdminId: string,
    projectId: string
  ): Promise<{
    projectId: string;
    deleted: Awaited<ReturnType<typeof cascadeDeleteProjectResources>>;
  }> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');

    const deleted = await cascadeDeleteProjectResources(doc._id);
    await ProjectModel.deleteOne({ _id: doc._id });
    return { projectId: doc._id.toString(), deleted };
  }

  async assertUsableForTenantService(params: {
    projectId: string;
    tenantId: string;
    serviceKey: AdminServiceKey;
  }): Promise<{ projectId: mongoose.Types.ObjectId; tenantId: string }> {
    if (!mongoose.Types.ObjectId.isValid(params.projectId)) {
      throw new ValidationError('Invalid projectId.');
    }
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(params.projectId),
      ownerType: 'tenant',
      tenantId: params.tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'active') {
      throw new ValidationError('Project is archived and cannot accept new resources.');
    }
    if (!doc.enabledServices.includes(params.serviceKey)) {
      throw new ValidationError(
        `Service "${params.serviceKey}" is not enabled on this project.`
      );
    }
    return { projectId: doc._id, tenantId: params.tenantId };
  }

  async listActiveForTenantService(
    tenantId: string,
    serviceKey: AdminServiceKey
  ): Promise<ProjectPublic[]> {
    const docs = await ProjectModel.find({
      ownerType: 'tenant',
      tenantId,
      status: 'active',
      enabledServices: serviceKey,
    }).sort({ createdAt: -1 });
    return docs.map((d) => toPublic(d));
  }

  async reportByProjectForTenant(tenantId: string): Promise<ProjectReportByProjectRow[]> {
    const tenantOid = new mongoose.Types.ObjectId(tenantId);
    const rows = await WalletTransaction.aggregate<{
      _id: mongoose.Types.ObjectId | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      { $match: { type: 'debit', tenantId: tenantOid } },
      {
        $group: {
          _id: '$projectId',
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    const projectIds = rows
      .map((r) => r._id)
      .filter((id): id is mongoose.Types.ObjectId => Boolean(id));
    const projects = await ProjectModel.find({
      _id: { $in: projectIds },
      ownerType: 'tenant',
      tenantId,
    })
      .select('name clientName')
      .lean();
    const byId = new Map(projects.map((p) => [p._id.toString(), p]));

    return rows.map((r) => {
      const id = r._id?.toString() ?? null;
      const project = id ? byId.get(id) : undefined;
      return {
        projectId: id,
        projectName: project?.name ?? (id ? null : 'Unassigned'),
        clientName: project?.clientName ?? null,
        totalDebit: Math.round(r.totalDebit * 100) / 100,
        transactionCount: r.transactionCount,
      };
    });
  }

  async reportByServiceForTenant(
    tenantId: string,
    projectId?: string
  ): Promise<ProjectReportByServiceRow[]> {
    const match: Record<string, unknown> = {
      type: 'debit',
      tenantId: new mongoose.Types.ObjectId(tenantId),
    };
    if (projectId) match.projectId = new mongoose.Types.ObjectId(projectId);

    const rows = await WalletTransaction.aggregate<{
      _id: string | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      { $match: match },
      {
        $group: {
          _id: { $ifNull: ['$serviceKey', '$reason'] },
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    return rows.map((r) => ({
      serviceKey: r._id || 'unknown',
      totalDebit: Math.round(r.totalDebit * 100) / 100,
      transactionCount: r.transactionCount,
    }));
  }

  async update(
    userId: string,
    projectId: string,
    input: UpdateProjectInput
  ): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be edited.');
    }

    applyProjectUpdateFields(doc, input);
    await applySupportAgentUpdate(doc, input.supportAgentId);
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublicWithAgent(doc, resourceCounts);
  }

  async addServices(
    userId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }

    const allowed = await getActiveOrgServiceKeys(orgId);
    const toAdd = assertServicesSubset(input.services, allowed);
    const merged = new Set([...doc.enabledServices, ...toAdd]);
    doc.enabledServices = [...merged] as AdminServiceKey[];
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async removeService(
    userId: string,
    projectId: string,
    serviceKey: string
  ): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    if (!isAdminServiceKey(serviceKey)) {
      throw new ValidationError(`Unknown service "${serviceKey}".`);
    }

    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    if (!doc.enabledServices.includes(serviceKey)) {
      throw new ValidationError(`Service "${serviceKey}" is not enabled on this project.`);
    }

    const count = await countResourcesForService(doc._id, serviceKey);
    if (count > 0) {
      throw new ValidationError(
        `Cannot remove "${serviceKey}" while ${count} resource(s) exist under this project.`
      );
    }

    doc.enabledServices = doc.enabledServices.filter((k) => k !== serviceKey);
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async archive(userId: string, projectId: string): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    markProjectArchived(doc, 'manual');
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async unarchive(userId: string, projectId: string): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'archived') {
      throw new ValidationError('Project is not archived.');
    }
    markProjectUnarchived(doc);
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  /**
   * Validate that a project is active, belongs to the org, and has the service enabled.
   * Used by billable resource create paths.
   */
  async assertUsableForService(params: {
    projectId: string;
    actingUserId: string;
    serviceKey: AdminServiceKey;
  }): Promise<{ projectId: mongoose.Types.ObjectId; orgId: string }> {
    const user = await User.findById(params.actingUserId)
      .select('role orgOwnerId isActive')
      .lean();
    if (!user || !user.isActive || user.role !== 'admin') {
      throw new ForbiddenError('Only organization admins can use projects.');
    }
    const orgId = resolvePlatformOrgOwnerId({
      _id: user._id,
      role: user.role,
      orgOwnerId: user.orgOwnerId,
    });
    if (!orgId) throw new ForbiddenError('Organization context required.');

    if (!mongoose.Types.ObjectId.isValid(params.projectId)) {
      throw new ValidationError('Invalid projectId.');
    }

    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(params.projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'active') {
      throw new ValidationError('Project is archived and cannot accept new resources.');
    }
    if (!doc.enabledServices.includes(params.serviceKey)) {
      throw new ValidationError(
        `Service "${params.serviceKey}" is not enabled on this project.`
      );
    }
    return { projectId: doc._id, orgId };
  }

  async listActiveForService(
    userId: string,
    serviceKey: AdminServiceKey
  ): Promise<ProjectPublic[]> {
    const user = await User.findById(userId).select('role orgOwnerId isActive').lean();
    if (!user || !user.isActive || user.role !== 'admin') {
      throw new ForbiddenError('Only organization admins can list projects.');
    }
    const orgId = resolvePlatformOrgOwnerId({
      _id: user._id,
      role: user.role,
      orgOwnerId: user.orgOwnerId,
    });
    if (!orgId) throw new ForbiddenError('Organization context required.');

    // Org owners manage projects; operators may still attach resources if they can create them.
    // Listing for pickers is allowed for any org admin under the owner org.
    const docs = await ProjectModel.find({
      orgId,
      status: 'active',
      enabledServices: serviceKey,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
      $and: [{ $or: [{ tenantId: { $exists: false } }, { tenantId: null }] }],
    }).sort({ createdAt: -1 });
    return docs.map((d) => toPublic(d));
  }

  async reportByProject(userId: string): Promise<ProjectReportByProjectRow[]> {
    const { orgId } = await assertOrgOwner(userId);
    const orgOid = new mongoose.Types.ObjectId(orgId);

    const rows = await AdminWalletTransaction.aggregate<{
      _id: mongoose.Types.ObjectId | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      {
        $match: {
          type: 'debit',
          $or: [{ orgId: orgOid }, { userId: orgOid }],
        },
      },
      {
        $group: {
          _id: '$projectId',
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    const projectIds = rows
      .map((r) => r._id)
      .filter((id): id is mongoose.Types.ObjectId => Boolean(id));
    const projects = await ProjectModel.find({ _id: { $in: projectIds }, orgId })
      .select('name clientName')
      .lean();
    const byId = new Map(projects.map((p) => [p._id.toString(), p]));

    return rows.map((r) => {
      const id = r._id?.toString() ?? null;
      const project = id ? byId.get(id) : undefined;
      return {
        projectId: id,
        projectName: project?.name ?? (id ? null : 'Unassigned'),
        clientName: project?.clientName ?? null,
        totalDebit: Math.round(r.totalDebit * 100) / 100,
        transactionCount: r.transactionCount,
      };
    });
  }

  async reportByService(
    userId: string,
    projectId?: string
  ): Promise<ProjectReportByServiceRow[]> {
    const { orgId } = await assertOrgOwner(userId);
    const orgOid = new mongoose.Types.ObjectId(orgId);

    const match: Record<string, unknown> = {
      type: 'debit',
      $or: [{ orgId: orgOid }, { userId: orgOid }],
    };
    if (projectId) {
      match.projectId = new mongoose.Types.ObjectId(projectId);
    }

    const rows = await AdminWalletTransaction.aggregate<{
      _id: string | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      { $match: match },
      {
        $group: {
          _id: { $ifNull: ['$serviceKey', '$reason'] },
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    return rows.map((r) => ({
      serviceKey: r._id || 'unknown',
      totalDebit: Math.round(r.totalDebit * 100) / 100,
      transactionCount: r.transactionCount,
    }));
  }

  async catalogServices(): Promise<AdminServiceKey[]> {
    const keys = await serviceCatalogService.listAssignableKeys('admin');
    return keys.filter(isAdminServiceKey);
  }

  /** Super-admin: update a project belonging to an org admin. */
  async updateForAdminBySuperAdmin(
    adminId: string,
    projectId: string,
    input: UpdateProjectInput
  ): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(adminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be edited.');
    }
    applyProjectUpdateFields(doc, input);
    await applySupportAgentUpdate(doc, input.supportAgentId);
    await doc.save();
    return toPublicWithAgent(doc, await resourceCountsByService(doc));
  }

  async listActiveSupportAgents(): Promise<ProjectSupportAgentPublic[]> {
    const agents = await User.find({ role: 'support_agent', isActive: true })
      .select('name email')
      .sort({ name: 1, email: 1 })
      .lean();
    return agents.map((agent) => ({
      id: agent._id.toString(),
      name: agent.name?.trim() || agent.email,
      email: agent.email,
    }));
  }

  /** Super-admin: all active support agents for create-modal dropdown. */
  async listSupportAgentsListForSuperAdmin(): Promise<
    Array<{ _id: string; name: string; email: string }>
  > {
    const agents = await User.find({ role: 'support_agent', isActive: true })
      .select('name email')
      .sort({ name: 1, email: 1 })
      .lean();
    return agents.map((agent) => ({
      _id: agent._id.toString(),
      name: agent.name?.trim() || agent.email,
      email: agent.email,
    }));
  }

  /** Org owner: list active support agents for project assignment. */
  async listSupportAgentsForOrgOwner(userId: string): Promise<ProjectSupportAgentPublic[]> {
    await assertOrgOwner(userId);
    return this.listActiveSupportAgents();
  }

  /** Org owner: support tickets linked to one org project. */
  async listSupportTicketsForProject(
    userId: string,
    projectId: string
  ): Promise<ProjectSupportTicketRow[]> {
    const { orgId } = await assertOrgOwner(userId);
    const project = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    }).select('_id');
    if (!project) {
      throw new NotFoundError('Project not found.');
    }

    const tickets = await Ticket.find({ projectId: project._id })
      .sort({ createdAt: -1 })
      .limit(100)
      .select('ticketNumber subject status platformAssigneeName createdAt')
      .lean();

    return tickets.map((t) => ({
      id: t._id.toString(),
      ticketNumber: t.ticketNumber,
      subject: t.subject,
      status: t.status,
      platformAssigneeName: t.platformAssigneeName?.trim() || null,
      createdAt: t.createdAt.toISOString(),
    }));
  }

  /** Tenant admin: list active support agents for project assignment. */
  async listSupportAgentsForTenantAdmin(role: string): Promise<ProjectSupportAgentPublic[]> {
    if (role !== 'tenant_admin') {
      throw new ForbiddenError('Only tenant administrators can list support agents.');
    }
    return this.listActiveSupportAgents();
  }

  /** Returns distinct client names already used in projects for this org. */
  async distinctClientNames(userId: string): Promise<string[]> {
    const { orgId } = await assertOrgOwner(userId);
    const names: string[] = await ProjectModel.distinct('clientName', {
      orgId,
      $or: [
        { ownerType: 'org' },
        { ownerType: { $exists: false } },
        { ownerType: null },
      ],
    });
    return names
      .filter((n): n is string => typeof n === 'string' && n.trim().length > 0)
      .sort((a, b) => a.localeCompare(b));
  }
}

export const projectsService = new ProjectsService();
