import mongoose from 'mongoose';
import { ProjectModel, type IProject, type ProjectOwnerType, type ProjectStatus } from '../../models/project.model';
import { OrganizationAccessRequestModel } from '../../models/organizationAccessRequest.model';
import { User } from '../../models/user.model';
import { Tenant } from '../../models/tenant.model';
import { CatalogVmModel } from '../../models/catalogVm.model';
import { DedicatedServerRequestModel } from '../../models/dedicatedServerRequest.model';
import { ExternalVMModel } from '../external-vm/external-vm.model';
import { VM } from '../vm/vm.model';
import { AdminWalletTransaction } from '../../models/adminWalletTransaction.model';
import { WalletTransaction } from '../../models/walletTransaction.model';
import {
  ADMIN_SERVICE_CATALOG,
  type AdminServiceKey,
  isAdminServiceKey,
} from '../../constants/adminServiceCatalog';
import { adminServicesService } from '../adminServices/adminServices.service';
import { tenantServiceConfigService } from '../tenant/tenantServiceConfig.service';
import { resolvePlatformOrgOwnerId } from '../platformRbac/platformRbac.service';
import {
  ForbiddenError,
  NotFoundError,
  ValidationError,
} from '../../utils/errors';
import type {
  AddProjectServicesInput,
  CreateProjectInput,
  UpdateProjectInput,
} from './projects.validation';

export interface ProjectPublic {
  id: string;
  ownerType: ProjectOwnerType;
  orgId: string | null;
  tenantId: string | null;
  name: string;
  autoGeneratedName: string;
  year: number;
  sequenceNumber: number;
  clientName: string;
  description: string | null;
  enabledServices: AdminServiceKey[];
  status: ProjectStatus;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  resourceCounts?: Record<string, number>;
}

export interface ProjectReportByProjectRow {
  projectId: string | null;
  projectName: string | null;
  clientName: string | null;
  totalDebit: number;
  transactionCount: number;
}

export interface ProjectReportByServiceRow {
  serviceKey: string;
  totalDebit: number;
  transactionCount: number;
}

function toPublic(doc: IProject, resourceCounts?: Record<string, number>): ProjectPublic {
  return {
    id: doc._id.toString(),
    ownerType: doc.ownerType || 'org',
    orgId: doc.orgId ?? null,
    tenantId: doc.tenantId ?? null,
    name: doc.name,
    autoGeneratedName: doc.autoGeneratedName,
    year: doc.year,
    sequenceNumber: doc.sequenceNumber,
    clientName: doc.clientName,
    description: doc.description ?? null,
    enabledServices: [...doc.enabledServices],
    status: doc.status,
    createdBy: doc.createdBy.toString(),
    createdAt: doc.createdAt.toISOString(),
    updatedAt: doc.updatedAt.toISOString(),
    ...(resourceCounts ? { resourceCounts } : {}),
  };
}

function slugifyOrgName(raw: string): string {
  const slug = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return slug || 'org';
}

async function resolveOrgSlug(orgId: string): Promise<string> {
  const access = await OrganizationAccessRequestModel.findOne({
    userId: new mongoose.Types.ObjectId(orgId),
    status: 'approved',
  })
    .select('companyName')
    .lean();
  if (access?.companyName) return slugifyOrgName(access.companyName);

  const user = await User.findById(orgId).select('email').lean();
  if (user?.email) {
    const local = String(user.email).split('@')[0] || 'org';
    return slugifyOrgName(local);
  }
  return 'org';
}

function padSequence(n: number): string {
  return String(n).padStart(3, '0');
}

async function resolveTenantSlug(tenantId: string): Promise<string> {
  const tenant = await Tenant.findById(tenantId).select('name slug').lean();
  if (tenant?.slug) return slugifyOrgName(tenant.slug);
  if (tenant?.name) return slugifyOrgName(tenant.name);
  return 'tenant';
}

async function assertTenantExists(tenantId: string): Promise<void> {
  if (!mongoose.Types.ObjectId.isValid(tenantId)) {
    throw new ValidationError('Invalid tenant id.');
  }
  const tenant = await Tenant.findById(tenantId).select('_id').lean();
  if (!tenant) throw new NotFoundError('Tenant not found.');
}

async function nextSequenceForOwner(params: {
  ownerType: ProjectOwnerType;
  orgId?: string;
  tenantId?: string;
  year: number;
}): Promise<number> {
  const filter =
    params.ownerType === 'tenant'
      ? { ownerType: 'tenant' as const, tenantId: params.tenantId, year: params.year }
      : { ownerType: 'org' as const, orgId: params.orgId, year: params.year };
  const latest = await ProjectModel.findOne(filter)
    .sort({ sequenceNumber: -1 })
    .select('sequenceNumber')
    .lean();
  return (latest?.sequenceNumber ?? 0) + 1;
}

async function nextSequence(orgId: string, year: number): Promise<number> {
  return nextSequenceForOwner({ ownerType: 'org', orgId, year });
}

async function assertOrgOwner(userId: string): Promise<{ orgId: string }> {
  const user = await User.findById(userId).select('role orgOwnerId isActive').lean();
  if (!user || !user.isActive || user.role !== 'admin') {
    throw new ForbiddenError('Only organization admins can manage projects.');
  }
  if (user.orgOwnerId) {
    throw new ForbiddenError('Only the organization owner can manage projects.');
  }
  const orgId = resolvePlatformOrgOwnerId({
    _id: user._id,
    role: user.role,
    orgOwnerId: user.orgOwnerId,
  });
  if (!orgId) throw new ForbiddenError('Organization context required.');
  return { orgId };
}

/** Resolve org owner id for super-admin acting on a customer admin. */
async function resolveTargetOrgOwnerId(adminId: string): Promise<string> {
  if (!mongoose.Types.ObjectId.isValid(adminId)) {
    throw new ValidationError('Invalid admin id.');
  }
  const user = await User.findById(adminId).select('role orgOwnerId isActive').lean();
  if (!user || !user.isActive || user.role !== 'admin') {
    throw new NotFoundError('Organization admin not found.');
  }
  if (user.orgOwnerId) {
    throw new ValidationError(
      'Projects belong to the organization owner. Open the owner account, not an operator.'
    );
  }
  const orgId = resolvePlatformOrgOwnerId({
    _id: user._id,
    role: user.role,
    orgOwnerId: user.orgOwnerId,
  });
  if (!orgId) throw new ValidationError('Organization context required.');
  return orgId;
}

async function createForOrg(
  orgId: string,
  createdByUserId: string,
  input: CreateProjectInput
): Promise<ProjectPublic> {
  const allowed = await getActiveOrgServiceKeys(orgId);
  const enabledServices = assertServicesSubset(input.enabledServices, allowed);

  const year = new Date().getUTCFullYear();
  const sequenceNumber = await nextSequenceForOwner({ ownerType: 'org', orgId, year });
  const slug = await resolveOrgSlug(orgId);
  const autoGeneratedName = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
  const name = (input.name?.trim() || autoGeneratedName).slice(0, 200);

  const doc = await ProjectModel.create({
    ownerType: 'org',
    orgId,
    name,
    autoGeneratedName,
    year,
    sequenceNumber,
    clientName: input.clientName.trim(),
    description: input.description?.trim() || undefined,
    enabledServices,
    status: 'active',
    createdBy: new mongoose.Types.ObjectId(createdByUserId),
  });

  return toPublic(doc, Object.fromEntries(enabledServices.map((k) => [k, 0])));
}

async function createForTenant(
  tenantId: string,
  createdByUserId: string,
  input: CreateProjectInput
): Promise<ProjectPublic> {
  const allowed = await getActiveTenantServiceKeys(tenantId);
  const enabledServices = assertServicesSubset(input.enabledServices, allowed);

  const year = new Date().getUTCFullYear();
  const sequenceNumber = await nextSequenceForOwner({ ownerType: 'tenant', tenantId, year });
  const slug = await resolveTenantSlug(tenantId);
  const autoGeneratedName = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
  const name = (input.name?.trim() || autoGeneratedName).slice(0, 200);

  const doc = await ProjectModel.create({
    ownerType: 'tenant',
    tenantId,
    name,
    autoGeneratedName,
    year,
    sequenceNumber,
    clientName: input.clientName.trim(),
    description: input.description?.trim() || undefined,
    enabledServices,
    status: 'active',
    createdBy: new mongoose.Types.ObjectId(createdByUserId),
  });

  return toPublic(doc, Object.fromEntries(enabledServices.map((k) => [k, 0])));
}

async function getActiveOrgServiceKeys(orgId: string): Promise<Set<AdminServiceKey>> {
  const services = await adminServicesService.listMine(new mongoose.Types.ObjectId(orgId));
  return new Set(
    services
      .filter((s) => s.status === 'active')
      .map((s) => s.serviceKey)
      .filter(isAdminServiceKey)
      // Documentation is not a billable/resource project service.
      .filter((key) => key !== 'docs')
  );
}

async function getActiveTenantServiceKeys(tenantId: string): Promise<Set<AdminServiceKey>> {
  const services = await tenantServiceConfigService.listServicesForTenant(tenantId);
  return new Set(
    services
      .filter((s) => s.status === 'active')
      .map((s) => s.serviceKey)
      .filter(isAdminServiceKey)
      .filter((key) => key !== 'docs')
  );
}

function assertServicesSubset(
  requested: string[],
  allowed: Set<AdminServiceKey>
): AdminServiceKey[] {
  const out: AdminServiceKey[] = [];
  for (const key of requested) {
    if (!isAdminServiceKey(key)) {
      throw new ValidationError(`Unknown service "${key}".`);
    }
    if (!allowed.has(key)) {
      throw new ValidationError(
        `Service "${key}" is not enabled for this organization.`
      );
    }
    if (!out.includes(key)) out.push(key);
  }
  return out;
}

async function countResourcesForService(
  projectId: mongoose.Types.ObjectId,
  serviceKey: AdminServiceKey
): Promise<number> {
  switch (serviceKey) {
    case 'create-vm':
      return CatalogVmModel.countDocuments({ projectId });
    case 'dedicated-server':
      return DedicatedServerRequestModel.countDocuments({ projectId });
    case 'vm-management':
      return VM.countDocuments({ projectId });
    case 'elastic-servers':
      return ExternalVMModel.countDocuments({ projectId });
    default:
      // Azure/AWS/GCP not stamped in V1 — treat as zero until wired.
      return 0;
  }
}

async function resourceCountsByService(
  project: IProject
): Promise<Record<string, number>> {
  const counts: Record<string, number> = {};
  for (const key of project.enabledServices) {
    counts[key] = await countResourcesForService(project._id, key);
  }
  return counts;
}

export class ProjectsService {
  async previewName(userId: string): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const { orgId } = await assertOrgOwner(userId);
    return this.previewNameForOrg(orgId);
  }

  async previewNameForOrg(
    orgId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const year = new Date().getUTCFullYear();
    const sequenceNumber = await nextSequence(orgId, year);
    const slug = await resolveOrgSlug(orgId);
    const name = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
    return { name, year, sequenceNumber };
  }

  async list(userId: string): Promise<ProjectPublic[]> {
    const { orgId } = await assertOrgOwner(userId);
    return this.listForOrg(orgId);
  }

  async listForOrg(orgId: string): Promise<ProjectPublic[]> {
    const oid = String(orgId);

    // Backfill legacy org projects created before ownerType existed.
    await ProjectModel.updateMany(
      {
        orgId: oid,
        $or: [{ ownerType: { $exists: false } }, { ownerType: null }],
        $and: [
          {
            $or: [{ tenantId: { $exists: false } }, { tenantId: null }, { tenantId: '' }],
          },
        ],
      },
      { $set: { ownerType: 'org' } }
    );

    const docs = await ProjectModel.find({
      orgId: oid,
      $and: [
        {
          $or: [
            { ownerType: 'org' },
            { ownerType: { $exists: false } },
            { ownerType: null },
          ],
        },
        {
          $or: [{ tenantId: { $exists: false } }, { tenantId: null }, { tenantId: '' }],
        },
      ],
    }).sort({ createdAt: -1 });

    return docs.map((d) => toPublic(d));
  }

  async getById(userId: string, projectId: string): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async create(userId: string, input: CreateProjectInput): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    return createForOrg(orgId, userId, input);
  }

  /** Super-admin: list projects for an organization owner admin. */
  async listForAdmin(targetAdminId: string): Promise<ProjectPublic[]> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const projects = await this.listForOrg(orgId);
    return projects;
  }

  /** Super-admin: preview next project name for an organization. */
  async previewNameForAdmin(
    targetAdminId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    return this.previewNameForOrg(orgId);
  }

  /** Super-admin: create a project owned by the organization (visible to org admin). */
  async createForAdmin(
    targetAdminId: string,
    createdByUserId: string,
    input: CreateProjectInput
  ): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    return createForOrg(orgId, createdByUserId, input);
  }

  /** Super-admin: active project-eligible services for an org. */
  async listEligibleServicesForAdmin(targetAdminId: string): Promise<AdminServiceKey[]> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    return [...(await getActiveOrgServiceKeys(orgId))];
  }

  /** Super-admin: add services to an org project. */
  async addServicesForAdmin(
    targetAdminId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    if (!doc.ownerType) {
      doc.ownerType = 'org';
    }

    const allowed = await getActiveOrgServiceKeys(orgId);
    const toAdd = assertServicesSubset(input.services, allowed);
    const merged = new Set([...doc.enabledServices, ...toAdd]);
    doc.enabledServices = [...merged] as AdminServiceKey[];
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  /** Super-admin: project detail for an organization. */
  async getByIdForAdmin(targetAdminId: string, projectId: string): Promise<ProjectPublic> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    });
    if (!doc) throw new NotFoundError('Project not found.');
    return toPublic(doc, await resourceCountsByService(doc));
  }

  /** Super-admin: service-wise wallet usage for one org project. */
  async reportByServiceForAdmin(
    targetAdminId: string,
    projectId: string
  ): Promise<ProjectReportByServiceRow[]> {
    const orgId = await resolveTargetOrgOwnerId(targetAdminId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
    })
      .select('_id')
      .lean();
    if (!doc) throw new NotFoundError('Project not found.');

    const orgOid = new mongoose.Types.ObjectId(orgId);
    const rows = await AdminWalletTransaction.aggregate<{
      _id: string | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      {
        $match: {
          type: 'debit',
          projectId: doc._id,
          $or: [{ orgId: orgOid }, { userId: orgOid }],
        },
      },
      {
        $group: {
          _id: { $ifNull: ['$serviceKey', '$reason'] },
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    return rows.map((r) => ({
      serviceKey: r._id || 'unknown',
      totalDebit: Math.round(r.totalDebit * 100) / 100,
      transactionCount: r.transactionCount,
    }));
  }

  /** Super-admin: add services to a tenant project. */
  async addServicesForTenantBySuperAdmin(
    tenantId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    await assertTenantExists(tenantId);
    return this.addServicesForTenant(tenantId, projectId, input);
  }

  /** Super-admin: list projects for a white-label tenant. */
  async listForTenantBySuperAdmin(tenantId: string): Promise<ProjectPublic[]> {
    await assertTenantExists(tenantId);
    return this.listForTenant(tenantId);
  }

  async previewNameForTenantBySuperAdmin(
    tenantId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    await assertTenantExists(tenantId);
    return this.previewNameForTenant(tenantId);
  }

  async createForTenantBySuperAdmin(
    tenantId: string,
    createdByUserId: string,
    input: CreateProjectInput
  ): Promise<ProjectPublic> {
    await assertTenantExists(tenantId);
    return createForTenant(tenantId, createdByUserId, input);
  }

  async listEligibleServicesForTenantBySuperAdmin(tenantId: string): Promise<AdminServiceKey[]> {
    await assertTenantExists(tenantId);
    return this.listEligibleServicesForTenant(tenantId);
  }

  async listForTenant(tenantId: string): Promise<ProjectPublic[]> {
    const docs = await ProjectModel.find({ ownerType: 'tenant', tenantId }).sort({
      createdAt: -1,
    });
    return docs.map((d) => toPublic(d));
  }

  async previewNameForTenant(
    tenantId: string
  ): Promise<{ name: string; year: number; sequenceNumber: number }> {
    const year = new Date().getUTCFullYear();
    const sequenceNumber = await nextSequenceForOwner({ ownerType: 'tenant', tenantId, year });
    const slug = await resolveTenantSlug(tenantId);
    const name = `${slug}-${year}-project-${padSequence(sequenceNumber)}`;
    return { name, year, sequenceNumber };
  }

  async createForTenantWorkspace(
    tenantId: string,
    createdByUserId: string,
    input: CreateProjectInput
  ): Promise<ProjectPublic> {
    return createForTenant(tenantId, createdByUserId, input);
  }

  async listEligibleServicesForTenant(tenantId: string): Promise<AdminServiceKey[]> {
    return [...(await getActiveTenantServiceKeys(tenantId))];
  }

  async getByIdForTenant(tenantId: string, projectId: string): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async updateForTenant(
    tenantId: string,
    projectId: string,
    input: UpdateProjectInput
  ): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be edited.');
    }
    if (input.name !== undefined) doc.name = input.name.trim();
    if (input.clientName !== undefined) doc.clientName = input.clientName.trim();
    if (input.description !== undefined) {
      doc.description = input.description?.trim() || undefined;
    }
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async addServicesForTenant(
    tenantId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    const allowed = await getActiveTenantServiceKeys(tenantId);
    const toAdd = assertServicesSubset(input.services, allowed);
    doc.enabledServices = [...new Set([...doc.enabledServices, ...toAdd])] as AdminServiceKey[];
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async removeServiceForTenant(
    tenantId: string,
    projectId: string,
    serviceKey: string
  ): Promise<ProjectPublic> {
    if (!isAdminServiceKey(serviceKey)) {
      throw new ValidationError(`Unknown service "${serviceKey}".`);
    }
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    if (!doc.enabledServices.includes(serviceKey)) {
      throw new ValidationError(`Service "${serviceKey}" is not enabled on this project.`);
    }
    const count = await countResourcesForService(doc._id, serviceKey);
    if (count > 0) {
      throw new ValidationError(
        `Cannot remove "${serviceKey}" while ${count} resource(s) exist under this project.`
      );
    }
    doc.enabledServices = doc.enabledServices.filter((k) => k !== serviceKey);
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async archiveForTenant(tenantId: string, projectId: string): Promise<ProjectPublic> {
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      ownerType: 'tenant',
      tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    doc.status = 'archived';
    await doc.save();
    return toPublic(doc, await resourceCountsByService(doc));
  }

  async assertUsableForTenantService(params: {
    projectId: string;
    tenantId: string;
    serviceKey: AdminServiceKey;
  }): Promise<{ projectId: mongoose.Types.ObjectId; tenantId: string }> {
    if (!mongoose.Types.ObjectId.isValid(params.projectId)) {
      throw new ValidationError('Invalid projectId.');
    }
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(params.projectId),
      ownerType: 'tenant',
      tenantId: params.tenantId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'active') {
      throw new ValidationError('Project is archived and cannot accept new resources.');
    }
    if (!doc.enabledServices.includes(params.serviceKey)) {
      throw new ValidationError(
        `Service "${params.serviceKey}" is not enabled on this project.`
      );
    }
    return { projectId: doc._id, tenantId: params.tenantId };
  }

  async listActiveForTenantService(
    tenantId: string,
    serviceKey: AdminServiceKey
  ): Promise<ProjectPublic[]> {
    const docs = await ProjectModel.find({
      ownerType: 'tenant',
      tenantId,
      status: 'active',
      enabledServices: serviceKey,
    }).sort({ createdAt: -1 });
    return docs.map((d) => toPublic(d));
  }

  async reportByProjectForTenant(tenantId: string): Promise<ProjectReportByProjectRow[]> {
    const tenantOid = new mongoose.Types.ObjectId(tenantId);
    const rows = await WalletTransaction.aggregate<{
      _id: mongoose.Types.ObjectId | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      { $match: { type: 'debit', tenantId: tenantOid } },
      {
        $group: {
          _id: '$projectId',
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    const projectIds = rows
      .map((r) => r._id)
      .filter((id): id is mongoose.Types.ObjectId => Boolean(id));
    const projects = await ProjectModel.find({
      _id: { $in: projectIds },
      ownerType: 'tenant',
      tenantId,
    })
      .select('name clientName')
      .lean();
    const byId = new Map(projects.map((p) => [p._id.toString(), p]));

    return rows.map((r) => {
      const id = r._id?.toString() ?? null;
      const project = id ? byId.get(id) : undefined;
      return {
        projectId: id,
        projectName: project?.name ?? (id ? null : 'Unassigned'),
        clientName: project?.clientName ?? null,
        totalDebit: Math.round(r.totalDebit * 100) / 100,
        transactionCount: r.transactionCount,
      };
    });
  }

  async reportByServiceForTenant(
    tenantId: string,
    projectId?: string
  ): Promise<ProjectReportByServiceRow[]> {
    const match: Record<string, unknown> = {
      type: 'debit',
      tenantId: new mongoose.Types.ObjectId(tenantId),
    };
    if (projectId) match.projectId = new mongoose.Types.ObjectId(projectId);

    const rows = await WalletTransaction.aggregate<{
      _id: string | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      { $match: match },
      {
        $group: {
          _id: { $ifNull: ['$serviceKey', '$reason'] },
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    return rows.map((r) => ({
      serviceKey: r._id || 'unknown',
      totalDebit: Math.round(r.totalDebit * 100) / 100,
      transactionCount: r.transactionCount,
    }));
  }

  async update(
    userId: string,
    projectId: string,
    input: UpdateProjectInput
  ): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be edited.');
    }

    if (input.name !== undefined) doc.name = input.name.trim();
    if (input.clientName !== undefined) doc.clientName = input.clientName.trim();
    if (input.description !== undefined) {
      doc.description = input.description?.trim() || undefined;
    }
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async addServices(
    userId: string,
    projectId: string,
    input: AddProjectServicesInput
  ): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }

    const allowed = await getActiveOrgServiceKeys(orgId);
    const toAdd = assertServicesSubset(input.services, allowed);
    const merged = new Set([...doc.enabledServices, ...toAdd]);
    doc.enabledServices = [...merged] as AdminServiceKey[];
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async removeService(
    userId: string,
    projectId: string,
    serviceKey: string
  ): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    if (!isAdminServiceKey(serviceKey)) {
      throw new ValidationError(`Unknown service "${serviceKey}".`);
    }

    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status === 'archived') {
      throw new ValidationError('Archived projects cannot be updated.');
    }
    if (!doc.enabledServices.includes(serviceKey)) {
      throw new ValidationError(`Service "${serviceKey}" is not enabled on this project.`);
    }

    const count = await countResourcesForService(doc._id, serviceKey);
    if (count > 0) {
      throw new ValidationError(
        `Cannot remove "${serviceKey}" while ${count} resource(s) exist under this project.`
      );
    }

    doc.enabledServices = doc.enabledServices.filter((k) => k !== serviceKey);
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  async archive(userId: string, projectId: string): Promise<ProjectPublic> {
    const { orgId } = await assertOrgOwner(userId);
    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    doc.status = 'archived';
    await doc.save();
    const resourceCounts = await resourceCountsByService(doc);
    return toPublic(doc, resourceCounts);
  }

  /**
   * Validate that a project is active, belongs to the org, and has the service enabled.
   * Used by billable resource create paths.
   */
  async assertUsableForService(params: {
    projectId: string;
    actingUserId: string;
    serviceKey: AdminServiceKey;
  }): Promise<{ projectId: mongoose.Types.ObjectId; orgId: string }> {
    const user = await User.findById(params.actingUserId)
      .select('role orgOwnerId isActive')
      .lean();
    if (!user || !user.isActive || user.role !== 'admin') {
      throw new ForbiddenError('Only organization admins can use projects.');
    }
    const orgId = resolvePlatformOrgOwnerId({
      _id: user._id,
      role: user.role,
      orgOwnerId: user.orgOwnerId,
    });
    if (!orgId) throw new ForbiddenError('Organization context required.');

    if (!mongoose.Types.ObjectId.isValid(params.projectId)) {
      throw new ValidationError('Invalid projectId.');
    }

    const doc = await ProjectModel.findOne({
      _id: new mongoose.Types.ObjectId(params.projectId),
      orgId,
    });
    if (!doc) throw new NotFoundError('Project not found.');
    if (doc.status !== 'active') {
      throw new ValidationError('Project is archived and cannot accept new resources.');
    }
    if (!doc.enabledServices.includes(params.serviceKey)) {
      throw new ValidationError(
        `Service "${params.serviceKey}" is not enabled on this project.`
      );
    }
    return { projectId: doc._id, orgId };
  }

  async listActiveForService(
    userId: string,
    serviceKey: AdminServiceKey
  ): Promise<ProjectPublic[]> {
    const user = await User.findById(userId).select('role orgOwnerId isActive').lean();
    if (!user || !user.isActive || user.role !== 'admin') {
      throw new ForbiddenError('Only organization admins can list projects.');
    }
    const orgId = resolvePlatformOrgOwnerId({
      _id: user._id,
      role: user.role,
      orgOwnerId: user.orgOwnerId,
    });
    if (!orgId) throw new ForbiddenError('Organization context required.');

    // Org owners manage projects; operators may still attach resources if they can create them.
    // Listing for pickers is allowed for any org admin under the owner org.
    const docs = await ProjectModel.find({
      orgId,
      status: 'active',
      enabledServices: serviceKey,
      $or: [{ ownerType: 'org' }, { ownerType: { $exists: false } }, { ownerType: null }],
      $and: [{ $or: [{ tenantId: { $exists: false } }, { tenantId: null }] }],
    }).sort({ createdAt: -1 });
    return docs.map((d) => toPublic(d));
  }

  async reportByProject(userId: string): Promise<ProjectReportByProjectRow[]> {
    const { orgId } = await assertOrgOwner(userId);
    const orgOid = new mongoose.Types.ObjectId(orgId);

    const rows = await AdminWalletTransaction.aggregate<{
      _id: mongoose.Types.ObjectId | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      {
        $match: {
          type: 'debit',
          $or: [{ orgId: orgOid }, { userId: orgOid }],
        },
      },
      {
        $group: {
          _id: '$projectId',
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    const projectIds = rows
      .map((r) => r._id)
      .filter((id): id is mongoose.Types.ObjectId => Boolean(id));
    const projects = await ProjectModel.find({ _id: { $in: projectIds }, orgId })
      .select('name clientName')
      .lean();
    const byId = new Map(projects.map((p) => [p._id.toString(), p]));

    return rows.map((r) => {
      const id = r._id?.toString() ?? null;
      const project = id ? byId.get(id) : undefined;
      return {
        projectId: id,
        projectName: project?.name ?? (id ? null : 'Unassigned'),
        clientName: project?.clientName ?? null,
        totalDebit: Math.round(r.totalDebit * 100) / 100,
        transactionCount: r.transactionCount,
      };
    });
  }

  async reportByService(
    userId: string,
    projectId?: string
  ): Promise<ProjectReportByServiceRow[]> {
    const { orgId } = await assertOrgOwner(userId);
    const orgOid = new mongoose.Types.ObjectId(orgId);

    const match: Record<string, unknown> = {
      type: 'debit',
      $or: [{ orgId: orgOid }, { userId: orgOid }],
    };
    if (projectId) {
      match.projectId = new mongoose.Types.ObjectId(projectId);
    }

    const rows = await AdminWalletTransaction.aggregate<{
      _id: string | null;
      totalDebit: number;
      transactionCount: number;
    }>([
      { $match: match },
      {
        $group: {
          _id: { $ifNull: ['$serviceKey', '$reason'] },
          totalDebit: { $sum: '$amount' },
          transactionCount: { $sum: 1 },
        },
      },
      { $sort: { totalDebit: -1 } },
    ]);

    return rows.map((r) => ({
      serviceKey: r._id || 'unknown',
      totalDebit: Math.round(r.totalDebit * 100) / 100,
      transactionCount: r.transactionCount,
    }));
  }

  catalogServices(): AdminServiceKey[] {
    return [...ADMIN_SERVICE_CATALOG];
  }
}

export const projectsService = new ProjectsService();
