import type { CatalogVmResponse } from './vmCatalog.types';
import type { VmCatalogProvider } from '../../models/catalogVm.model';
import { ValidationError } from '../../utils/errors';

const SUPER_ADMIN_ONLY_FIELDS = [
  'provider',
  'region',
  'providerInstanceId',
  'rawProviderCostPerHr',
  'externalRef',
  'azureResourceGroup',
] as const;

export type CatalogVmCallerRole = 'super_admin' | 'admin' | 'user' | string;

/**
 * Strip infra-identity fields from catalog VM responses for non-super_admin callers.
 */
export function stripProviderLeakFields<T extends Partial<CatalogVmResponse>>(
  response: T,
  role: CatalogVmCallerRole | undefined
): T {
  if (role === 'super_admin') {
    return response;
  }

  const out = { ...response };
  for (const key of SUPER_ADMIN_ONLY_FIELDS) {
    delete out[key];
  }
  return out;
}

export function inferCategoryFromOsLabel(label: string): 'ubuntu' | 'rocky' | 'debian' | 'windows' | 'linux' | 'gpu' {
  const s = String(label || '').trim().toLowerCase();
  if (s.includes('windows')) return 'windows';
  if (s.includes('ubuntu')) return 'ubuntu';
  if (s.includes('rocky')) return 'rocky';
  if (s.includes('debian')) return 'debian';
  if (s.includes('gpu')) return 'gpu';
  return 'linux';
}

export function specsToCanonicalSpec(
  specs: { cpu?: string; ram?: string; disk?: string } | undefined,
  category: string
): string {
  const cpu = String(specs?.cpu || '').replace(/[^\d]/g, '') || '2';
  const ram = String(specs?.ram || '').replace(/[^\d]/g, '') || '8';
  const disk = String(specs?.disk || '').replace(/[^\d]/g, '') || '50';
  const base = `${cpu}vcpu-${ram}gb-${disk}gbssd`;
  return category === 'gpu' ? `${base}-gpu` : base;
}

export function planDimensionsToCanonicalSpec(
  vcpu: number,
  ramGb: number,
  ssdGb: number,
  category: string
): string {
  const base = `${vcpu}vcpu-${ramGb}gb-${ssdGb}gbssd`;
  return category === 'gpu' ? `${base}-gpu` : base;
}

/** Azure-safe resource group name (max 90 chars, allowed charset). */
export function sanitizeAzureResourceGroupName(name: string): string {
  let s = String(name || '')
    .trim()
    .replace(/\.$/, '')
    .replace(/[^A-Za-z0-9-_.()]/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 90);
  if (s.endsWith('.')) s = s.slice(0, -1);
  if (!s) {
    throw new ValidationError('Invalid Azure resource group name from project.');
  }
  return s;
}

/** VM resource group for a project — uses project display name, falls back to autoGeneratedName. */
export function projectAzureResourceGroupName(project: {
  name: string;
  autoGeneratedName: string;
}): string {
  const candidate = project.name?.trim() || project.autoGeneratedName?.trim();
  return sanitizeAzureResourceGroupName(candidate);
}

/**
 * Infer duration in days from billing period string or explicit durationDays.
 * hourly/daily → short (auto-cloud); monthly+ → webyne rule (>=30).
 */
export function resolveDurationDays(billing: string, explicit?: number): number {
  if (explicit != null && Number.isFinite(explicit) && explicit > 0) {
    return Math.floor(explicit);
  }
  const b = String(billing || '').toLowerCase();
  if (b.includes('year')) return 365;
  if (b.includes('quarter')) return 90;
  if (b.includes('month')) return 30;
  if (b.includes('week')) return 7;
  if (b.includes('day')) return 1;
  if (b.includes('hour')) return 1;
  return 30;
}

export function computeExpiresAt(durationDays: number): Date {
  const days = Math.max(1, durationDays);
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000);
}

export function isAutoCloudProvider(
  provider: string | undefined
): provider is 'aws' | 'azure' | 'oci' | 'gcp' {
  return (
    provider === 'aws' ||
    provider === 'azure' ||
    provider === 'oci' ||
    provider === 'gcp'
  );
}

export type { VmCatalogProvider };
