export const SERVICE_IAM_POLICIES = {
  'Compute Engine': ['roles/compute.instanceAdmin.v1', 'roles/compute.viewer'],
  'Cloud Run': ['roles/run.developer', 'roles/run.viewer'],
  'Cloud Functions': ['roles/cloudfunctions.developer', 'roles/cloudfunctions.viewer'],
  'App Engine': ['roles/appengine.appAdmin', 'roles/appengine.appViewer'],
  'Cloud SQL': ['roles/cloudsql.client', 'roles/cloudsql.viewer'],
  Firestore: ['roles/datastore.user', 'roles/datastore.viewer'],
  'Cloud Spanner': ['roles/spanner.databaseUser', 'roles/spanner.viewer'],
  Memorystore: ['roles/redis.editor', 'roles/redis.viewer'],
  Bigtable: ['roles/bigtable.user', 'roles/bigtable.viewer'],
  'Cloud Storage': ['roles/storage.objectAdmin', 'roles/storage.objectViewer'],
  Filestore: ['roles/file.editor', 'roles/file.viewer'],
  GKE: ['roles/container.developer', 'roles/container.viewer'],
  'Artifact Registry': ['roles/artifactregistry.reader', 'roles/artifactregistry.repoAdmin'],
  VPC: ['roles/compute.networkAdmin', 'roles/compute.networkViewer'],
  'Cloud DNS': ['roles/dns.admin', 'roles/dns.reader'],
  'Cloud CDN': ['roles/compute.loadBalancerAdmin', 'roles/compute.viewer'],
  'Cloud Load Balancing': ['roles/compute.loadBalancerAdmin', 'roles/compute.viewer'],
  BigQuery: ['roles/bigquery.dataEditor', 'roles/bigquery.dataViewer'],
  Dataflow: ['roles/dataflow.developer', 'roles/dataflow.viewer'],
  Dataproc: ['roles/dataproc.editor', 'roles/dataproc.viewer'],
  'Pub/Sub': ['roles/pubsub.editor', 'roles/pubsub.viewer'],
  'Vertex AI': ['roles/aiplatform.user', 'roles/aiplatform.viewer'],
  'Cloud Vision': ['roles/visionai.viewer', 'roles/visionai.admin'],
  'Secret Manager': ['roles/secretmanager.admin', 'roles/secretmanager.viewer'],
  'Cloud KMS': ['roles/cloudkms.admin', 'roles/cloudkms.viewer'],
};

export const DEFAULT_IAM_POLICIES = {
  'Compute Engine': 'roles/compute.instanceAdmin.v1',
  'Cloud Run': 'roles/run.developer',
  'Cloud Functions': 'roles/cloudfunctions.developer',
  'App Engine': 'roles/appengine.appAdmin',
  'Cloud SQL': 'roles/cloudsql.client',
  Firestore: 'roles/datastore.user',
  'Cloud Spanner': 'roles/spanner.databaseUser',
  Memorystore: 'roles/redis.editor',
  Bigtable: 'roles/bigtable.user',
  'Cloud Storage': 'roles/storage.objectAdmin',
  Filestore: 'roles/file.editor',
  GKE: 'roles/container.developer',
  'Artifact Registry': 'roles/artifactregistry.reader',
  VPC: 'roles/compute.networkAdmin',
  'Cloud DNS': 'roles/dns.admin',
  'Cloud CDN': 'roles/compute.loadBalancerAdmin',
  'Cloud Load Balancing': 'roles/compute.loadBalancerAdmin',
  BigQuery: 'roles/bigquery.dataEditor',
  Dataflow: 'roles/dataflow.developer',
  Dataproc: 'roles/dataproc.editor',
  'Pub/Sub': 'roles/pubsub.editor',
  'Vertex AI': 'roles/aiplatform.user',
  'Cloud Vision': 'roles/visionai.viewer',
  'Secret Manager': 'roles/secretmanager.admin',
  'Cloud KMS': 'roles/cloudkms.admin',
};

export const FLAT_RATE_INFO = {
  'Cloud Storage': 'Billed per GB stored. Select a lab usage tier for the wallet estimate.',
  'Cloud Functions': 'Billed per invocation / GB-second. Select a lab usage tier.',
  Firestore: 'Billed by reads/writes. Select a lab usage tier.',
  BigQuery: 'Billed by data scanned. Select a lab query tier.',
  'Pub/Sub': 'Billed per message volume. Select a lab tier.',
  VPC: 'NAT and egress can incur charges. Select a lab network tier.',
  'Cloud CDN': 'Billed per GB egress. Select a lab tier.',
  'Cloud Run': 'Billed per vCPU-second. Select a lab tier.',
};
