export const SERVICE_IAM_POLICIES = {
  EC2: ['EC2FullAccess', 'EC2ReadOnlyAccess'],
  Lightsail: ['LightsailFullAccess', 'LightsailReadOnlyAccess'],
  RDS: ['RDSFullAccess', 'RDSReadOnlyAccess'],
  DynamoDB: ['DynamoDBFullAccess', 'DynamoDBReadOnlyAccess'],
  ElastiCache: ['ElastiCacheFullAccess', 'ElastiCacheReadOnlyAccess'],
  Redshift: ['RedshiftFullAccess', 'RedshiftReadOnlyAccess'],
  S3: ['S3FullAccess', 'S3ReadOnlyAccess'],
  EKS: ['EKSFullAccess', 'EKSReadOnlyAccess'],
  Lambda: ['LambdaFullAccess', 'LambdaReadOnlyAccess'],
  VPC: ['VPCFullAccess', 'VPCReadOnlyAccess'],
  CloudFront: ['CloudFrontFullAccess', 'CloudFrontReadOnlyAccess'],
  SQS: ['SQSFullAccess', 'SQSReadOnlyAccess'],
  SNS: ['SNSFullAccess', 'SNSReadOnlyAccess'],
  Kinesis: ['KinesisFullAccess', 'KinesisReadOnlyAccess'],
  EMR: ['EMRFullAccess', 'EMRReadOnlyAccess'],
  OpenSearch: ['OpenSearchFullAccess', 'OpenSearchReadOnlyAccess'],
  SageMaker: ['SageMakerFullAccess', 'SageMakerReadOnlyAccess'],
};

export const DEFAULT_IAM_POLICIES = {
  EC2: 'EC2FullAccess',
  Lightsail: 'LightsailFullAccess',
  RDS: 'RDSFullAccess',
  DynamoDB: 'DynamoDBFullAccess',
  ElastiCache: 'ElastiCacheFullAccess',
  Redshift: 'RedshiftFullAccess',
  S3: 'S3FullAccess',
  EKS: 'EKSFullAccess',
  Lambda: 'LambdaFullAccess',
  VPC: 'VPCFullAccess',
  CloudFront: 'CloudFrontFullAccess',
  SQS: 'SQSFullAccess',
  SNS: 'SNSFullAccess',
  Kinesis: 'KinesisFullAccess',
  EMR: 'EMRFullAccess',
  OpenSearch: 'OpenSearchFullAccess',
  SageMaker: 'SageMakerFullAccess',
};

export const FLAT_RATE_INFO = {
  S3: 'Billed per GB stored. Select a lab usage tier for the wallet estimate.',
  Lambda: 'Billed per GB-second of execution. Select a lab usage tier for the wallet estimate.',
  DynamoDB: 'Billed by on-demand read/write capacity. Select a lab usage tier for the wallet estimate.',
  CloudFront: 'Billed per GB transferred. Select a lab usage tier for the wallet estimate.',
  SQS: 'Billed per request. Select a lab usage tier for the wallet estimate.',
  SNS: 'Billed per notification. Select a lab usage tier for the wallet estimate.',
  Kinesis: 'Billed per shard-hour. Select a lab usage tier for the wallet estimate.',
  VPC: 'NAT Gateway and related networking can incur charges. Select a lab network tier for the wallet estimate.',
};
