import mongoose, { Document, Schema } from 'mongoose';
import type { AdminServiceKey } from '../constants/adminServiceCatalog';

export type ProjectStatus = 'active' | 'archived';
export type ProjectOwnerType = 'org' | 'tenant';

export interface IProject extends Document {
  _id: mongoose.Types.ObjectId;
  ownerType: ProjectOwnerType;
  /** Organization owner admin userId (string). Set when ownerType === 'org'. */
  orgId?: string;
  /** Tenant workspace id (string). Set when ownerType === 'tenant'. */
  tenantId?: string;
  name: string;
  autoGeneratedName: string;
  year: number;
  sequenceNumber: number;
  clientName: string;
  description?: string;
  startDate?: Date;
  endDate?: Date;
  enabledServices: AdminServiceKey[];
  status: ProjectStatus;
  /** Platform User or TenantUser id depending on creator. */
  createdBy: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const projectSchema = new Schema<IProject>(
  {
    ownerType: {
      type: String,
      enum: ['org', 'tenant'],
      default: 'org',
      required: true,
      index: true,
    },
    orgId: { type: String, index: true },
    tenantId: { type: String, index: true },
    name: { type: String, required: true, trim: true, maxlength: 200 },
    autoGeneratedName: { type: String, required: true, trim: true, maxlength: 200 },
    year: { type: Number, required: true, min: 2000, max: 2100 },
    sequenceNumber: { type: Number, required: true, min: 1 },
    clientName: { type: String, required: true, trim: true, maxlength: 200 },
    description: { type: String, trim: true, maxlength: 1000 },
    startDate: { type: Date },
    endDate: { type: Date },
    enabledServices: {
      type: [String],
      default: [],
    },
    status: {
      type: String,
      enum: ['active', 'archived'],
      default: 'active',
      index: true,
    },
    createdBy: { type: Schema.Types.ObjectId, required: true },
  },
  {
    timestamps: true,
    collection: 'projects',
  }
);

projectSchema.index(
  { orgId: 1, year: 1, sequenceNumber: 1 },
  { unique: true, partialFilterExpression: { ownerType: 'org', orgId: { $type: 'string' } } }
);
projectSchema.index(
  { tenantId: 1, year: 1, sequenceNumber: 1 },
  {
    unique: true,
    partialFilterExpression: { ownerType: 'tenant', tenantId: { $type: 'string' } },
  }
);
projectSchema.index({ orgId: 1, status: 1, createdAt: -1 });
projectSchema.index({ tenantId: 1, status: 1, createdAt: -1 });

export const ProjectModel = mongoose.model<IProject>('Project', projectSchema);
